//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimSocietyAdminApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Swimmer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Birthplace { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Sex { get; set; }
        public int AgeGroup_FK { get; set; }
        public int Club_FK { get; set; }
    
        public virtual Agegroup Agegroup { get; set; }
        public virtual Club Club { get; set; }
    }
}
